#Program for creatng calibration file

prompts = [
    "Describe the scene in the image.",
    "What is the person doing?",
    "How many objects are visible?",
    "What is the color of the sky?",
    "Summarize the image content.",
    "What kind of animal is shown?",
    "Is the weather sunny, cloudy, or rainy?",
    "Write a caption for this picture.",
    "What emotion does the scene convey?",
    "Describe the setting in one sentence.",
    "Is this indoors or outdoors?",
    "List the objects in this image.",
    "What activity is taking place?",
    "Identify the main subject of the photo.",
    "What time of day is it?",
    "What season does this image depict?",
    "Describe the facial expression.",
    "What is unusual in this image?",
    "Name the location shown.",
    "Where is my phone?",
    "What is the person wearing?",
    "Describe the mood of the image.",
    "What is in the background?",
    "What is the vehicle shown?",
    "Is this image real or artificial?",
    "What action is the animal performing?",
    "What kind of environment is this?",
    "How many people are in the image?",
    "What is the person holding?",
    "Where is the nearest exit?",
    "Write a social media caption.",
    "Describe the image from a child's perspective.",
    "Explain what is happening.",
    "What could this image be used for?",
    "Guess what happened before this moment.",
    "Describe the lighting conditions.",
    "What textures do you notice?",
    "Is there movement in the image?",
    "What kind of plant is visible?",
    "Describe the sky and clouds.",
    "Are there any hazards in this image?",
    "What is the person likely thinking?",
    "Is it safe to walk across the street?",
    "What sounds would you expect in this scene?",
    "Is this a drawing or a photograph?",
    "Is the subject in focus?",
    "Write a poetic caption for the scene.",
    "Is this related to nature or technology?",
    "What direction is the person facing?",
    "What is on the table?",
    "Describe the image using only nouns.",
    "What is in the foreground?",
    "Describe the use of symmetry.",
    "What is the source of light?",
    "What genre does this image belong to?",
    "Could this be part of a storybook?",
    "Describe it in five words.",
    "Name three visible objects.",
    "Is there any text in the image?",
    "What is the image resolution?",
    "Could this be used for advertising?",
    "What is happening in the background?",
    "Is there a shadow present?",
    "What is being shown on TV?",
    "Is there anything hidden?",
    "Is the image black and white or color?",
    "Write a newspaper headline for this scene.",
    "What decade might this be from?",
    "Describe the person’s posture.",
    "Does the image contain food?",
    "What does the image focus on?",
    "What camera angle was used?",
    "Describe the architecture shown.",
    "What kind of event is this?",
    "Is this a casual or formal setting?",
    "Describe the emotions on the faces.",
    "What kind of clothing is shown?",
    "Is the image cropped or full-frame?",
    "Describe this in the style of a novel.",
    "What kind of story can this image tell?",
    "Use one adjective to describe the image.",
    "Could this image be used in a textbook?",
    "What brand is shown in the image?",
    "Is the image symmetrical or asymmetrical?",
    "What is the scale of the objects?",
    "Is there water in the image?",
    "What art style does this resemble?",
    "Write a product description based on this image.",
    "What theme does this image explore?",
    "Describe this image as if to a blind person.",
    "What is happening at the edge of the frame?",
    "Is the image static or dynamic?",
    "Is there an animal in motion?",
    "Is the background blurred?",
    "What does the image suggest about society?",
    "Is this image humorous or serious?",
    "What technology is visible?",
    "What emotion does the color scheme evoke?",
    "Is this image edited or natural?",
    "Describe the object in the center.",
    "Is this image from a specific culture?",
    "Can you describe the image without nouns?",
    "Is the subject looking at the camera?",
    "What kind of message does this image send?",
    "Could this be part of a meme?",
    "Describe the symmetry or balance.",
    "What type of lens was likely used?",
    "Is there any writing in the image?",
    "What geometric shapes can be found?",
    "What color stands out the most?",
    "Write a short story based on the image.",
    "Describe the use of negative space.",
    "Is this photo staged or candid?",
    "How does the image make you feel?",
    "What emotion might the subject be feeling?",
    "What contrasts are visible in the image?",
    "Describe the light source and direction.",
    "Is the image zoomed in or wide-angle?",
    "What colors dominate the palette?",
    "How does the composition guide your eye?",
    "What details are easy to miss?",
    "Does the image suggest action or stillness?",
    "What clues tell you about the context?",
    "Is the image symmetrical or random?",
    "What’s one question this image raises?",
    "Is this a promotional or documentary image?",
    "What kind of people is this image intended for?",
    "What part of the image is most important?",
    "What happens if we crop the top half?"
]


# Write to file
with open("calib.txt", "w", encoding="utf-8") as f:
    for line in prompts:
        f.write(line.strip() + "\n")

print("Program completed.")